# COURSE: Master math by coding in Python
# SECTION: Algebra 1
# VIDEO: Creating and accessing matrices with numpy


### https://www.udemy.com/course/math-with-python/?couponCode=202312
#### INSTRUCTOR: Mike X Cohen (http://sincxpress.com)

This code roughly matches the code shown in the live recording: variable names, order of lines, and parameter settings may be slightly different.

<a target="_blank" href="https://colab.research.google.com/github/mikexcohen/MasterMathByCodingInPython/blob/main/algebra_1/mathWithPython_algebra1_matrices.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
# import libraries
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [2]:
A = np.array( [ [1,2],[3,4] ] )
print(A)

# make it look nicer
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [3]:
# initializing a matrix with zeros

numrange = range(0,5)

mat = np.zeros([len(numrange),len(numrange)])
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# populating matrices using row-col indexing

mat[0,1] = 1
# mat[5,8] = 4
mat

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# can also use variables for indices
i = 2
j = 1
mat[i,j] = 4.5

display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [6]:
# now use a for-loop

numrange = range(0,3)
for i in numrange:
  for j in numrange:
    mat[i][j] = (-1)**(i+j)

mat

array([[ 1., -1.,  1.,  0.,  0.],
       [-1.,  1., -1.,  0.,  0.],
       [ 1., -1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

# Exercise

In [7]:
x,y = sym.symbols('x y')
Fxy = (4+x)*(2-y)

numrange = range(0,3)

funout = np.zeros((len(numrange),len(numrange)))

for i in numrange:
  for j in numrange:
    funout[i,j] = Fxy.subs({x:i,y:j})

display(Math(sym.latex(sym.sympify(funout))))

<IPython.core.display.Math object>